[[news]]
date = "2026-05"
content = "🎉🎉 One paper was accepted by International Conference on Machine Learning 2026."

[[news]]
date = "2026-04"
content = "🎉🎉 One paper was accepted by IEEE Transactions on Artificial Intelligence 2026 Journal."

[[news]]
date = "2025-09"
content = "🎉🎉 One paper was accepted by IJCAI 2025 Survey track."

[[news]]
date = "2025-07"
content = "🎉🎉 One paper was accepted by Pattern Recognition Journal."


[[news]]
date = "2024-03"
content = "🎉🎉 One paper was accepted by Neural Networks Journal."


[[news]]
date = "2023-09"
content = "🎉🎉 One paper was accepted by ECML-PKDD 2023."

