[[news]]
date = "2026-05"
content = "🎉🎉 一篇论文被 International Conference on Machine Learning 2026 接收。"

[[news]]
date = "2026-04"
content = "🎉🎉 一篇论文被 IEEE Transactions on Artificial Intelligence 2026 Journal 接收。"

[[news]]
date = "2025-09"
content = "🎉🎉 一篇论文被 IJCAI 2025 Survey track 接收。"

[[news]]
date = "2025-07"
content = "🎉🎉 一篇论文被 Pattern Recognition Journal 接收。"

[[news]]
date = "2024-03"
content = "🎉🎉 一篇论文被 Neural Networks Journal 接收。"

[[news]]
date = "2023-09"
content = "🎉🎉 一篇论文被 ECML-PKDD 2023 接收。"
